image: ruby:2.3

cache:
  paths:
  - vendor/

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan dev.sush.us >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - gem install bundler

test_development:
  stage: test
  environment: Development
  only:
  - dev
  script:
  - bundle install --path=vendor/
  - JEKYLL_ENV=dev bundle exec jekyll build

deploy_development:
  stage: deploy
  environment: Development
  only:
  - dev
  except:
    variables:
      - $CI_COMMIT_TAG == "skip-pipeline"
  script:
  - ssh -t sush@dev.sush.us "cd $DEV_DIRECTORY;git pull;JEKYLL_ENV=dev jekyll build;"

#deploy_development_test:
#  stage: deploy
#  environment: Development
#  only:
#  - dev
#  script:
#  - 
