image: ruby:2.3

before_script:
  - bundle install

test_development:
  stage: test
  environment: Development
  only:
  - dev
  script:
  - bundle exec JEKYLL_ENV=dev jekyll build
  artifacts:
    paths:
    - test
