image: ruby:2.3

cache:
  paths:
  - vendor/

before_script:
  - bundle install --path vendor

test_development:
  stage: test
  environment: Development
  only:
  - dev
  script:
  - JEKYLL_ENV=dev jekyll build
  artifacts:
    paths:
    - test
