image: ruby:2.3

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec JEKYLL_ENV=dev jekyll build
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
