# Site

title: "An Experiment in Development"
description: ""
url: "https://sush.us"
url_dev: "https://dev.sush.us"
subscribe_rss: /feed.xml

# Personal information

email: "lorenzo.sapora@gmail.com"
author: "Lorenzo Sapora"
gpg_publickey: "/public.asc"
gpg_fingerprint: "ACF4 6F26 53D5 894C C074  4F8A CF91 90EF EB49 1E09"

twitter_username: "SudoSushi"
skype_username: "Lorenzo.Sapora"
linkedin_username: "lorenzo-s-43b77214b"
github_username: "LorenzoSapora"
gitlab_username: "LorenzoSapora"

# Build settings

destination: public
permalink: /log/:title/
markdown: kramdown
theme: 
plugins:
  - jekyll-feed
  - jekyll-html5-youtube

exclude: ["README.md"]
